### ISSUE TITLE
Consider creating a release

### ISSUE THREAD

**Issue by ocefpaf** [phobson/gridgen#1]
Hi @phobson would you consider creating a GitHub release?  That would make it easier to package the software by referring to a point in its history.  Using "master" branch in conda is a little awkward.

**Comment by phobson** [comment]
sure thing -- may I ask how your packaging what platforms you're targeting? (I'm trying to figure out how to get all of this stuff built for windows and it's a bit out of my league)

**Comment by ocefpaf** [comment]
Thanks!


> get all of this stuff built for windows and it's a bit out of my league

Same here...  but at least now we have two trying :grimacing: 

We are targeting OSX, Linux and Windows too.  Right now we do not have Windows builds for several packages (including gridgen).  Here are our recipes:

https://github.com/ioos/conda-recipes

I will ping you if I have any success on Windows.

**Comment by phobson** [comment]
https://github.com/phobson/gridgen/releases

i'm new to gihub releases too -- is that what you had in mind? I can do releases for the other libraries (gridutils, nn, csa).

Shameless plug: have you seen my `pygridtools` module? https://github.com/phobson/pygridtools

It just extends pygridgen a bit (focusing grids, merging grids, numeric transformations, shapefile I/O, integration with pandas, etc)

Cool example:

**Comment by ocefpaf** [comment]
> i'm new to gihub releases too -- is that what you had in mind?

Exactly!

> I can do releases for the other libraries (gridutils, nn, csa).

That would be awesome.   (I was going to ask that :wink: )

> Shameless plug: have you seen my pygridtools module?

Yes.  Great work BTW!  I have a recipe for it but haven't uploaded it yet.
